=== Open-Systems-Pharmacology/QualificationPlan/schemas/OSP_Qualification_Plan_Schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {

    "buildingBlockType": {
      "$id": "#buildingBlockType",
      "type": "string",
      "enum": ["Individual", "Population", "Compound", "Protocol", "Event", "Formulation", "ObserverSet"]
    },

    "buildingBlockOrSimulationType": {
      "anyOf": [
        { "$ref": "#/definitions/buildingBlockType" },
        { "type": "string", "enum": ["Simulation"] }
      ]
    },

    "fontSize": {"type": "integer", "minimum": 8, "maximum": 60},

    "rgbColor": {
      "type": "string",
      "description": "RGB color (hex)",
      "format":"regex",
      "pattern": "^#([a-fA-F0-9]{6})$",
      "example": "#aa33cc"
    },

    "timeUnit": {
      "type": "string",
      "enum": ["s", "min", "h", "day(s)", "week(s)", "month(s)", "year(s)"]
    },

    "nonEmptyString": { "type": "string", "minLength": 1 },

    "plotSize": { "type": "integer", "minimum": 200, "maximum": 2000 },

    "symbolType": {
      "type": "string",
      "enum": ["Circle", "Square", "Diamond", "Asterisk", "Point", "Cross", "Triangle"]
    },

    "positiveNumber": { "type": "number", "minimum": 0, "exclusiveMinimum": true },

    "nonNegativeNumber": { "type": "number", "minimum": 0 },

    "sections": {
      "type": "array",
      "items": 
        {
          "type": "object",
          "properties": {
            "Id": {"type": "integer"},
            "Title": { "$ref": "#/definitions/nonEmptyString" },
            "Content": {"type": "string", "format": "regex", "pattern": ".md$"},
            "Sections": { "$ref": "#/definitions/sections" }
          },
          "required": ["Id", "Title", "Content"]
        }
    }

  },

  "type": "object",
  "properties": {

    "Projects": {
      "type": "array",
      "items": 
        {
          "type": "object",
          "properties": {

            "Id": { "$ref": "#/definitions/nonEmptyString" },

            "Path": {"type": "string", "format": "regex", "pattern": ".json$"},

            "BuildingBlocks": {
              "type": "array",
              "items": 
                {
                  "type": "object",
                  "properties": {
                    "Type": { "$ref": "#/definitions/buildingBlockType" },
                    "Name": { "$ref": "#/definitions/nonEmptyString" },
                    "Project": { "$ref": "#/definitions/nonEmptyString" }
                  },
                  "required": ["Type", "Name", "Project"]
                }
            },

            "SimulationParameters": {
              "type": "array",
              "items": 
                {
                  "type": "object",
                  "properties": {
                    "Simulation": { "$ref": "#/definitions/nonEmptyString" },
                    "Path": { "$ref": "#/definitions/nonEmptyString" },
                    "SourceProject": { "$ref": "#/definitions/nonEmptyString" },
                    "SourceSimulation": { "$ref": "#/definitions/nonEmptyString" }
                  },
                  "required": ["Simulation", "Path", "SourceProject", "SourceSimulation"]
                }
            }
          },
          "required": ["Id", "Path"]
        }
    },

    "ObservedDataSets": {
      "type": "array",
      "items": 
        {
          "type": "object",
          "properties": {

            "Id": { "$ref": "#/definitions/nonEmptyString" },

            "Path": {"type": "string", "format": "regex", "pattern": ".csv$"},

            "Type": {
              "type": "string",
              "enum": ["DDIRatio", "PKRatio", "TimeProfile"]
            }
          },
          "required": ["Id", "Path", "Type"]
        }
    },

    "Plots": {
      "type": "object",
      "properties": {

        "PlotSettings": {
          "type": "object",
          "properties": {
            "ChartWidth": { "$ref": "#/definitions/plotSize" },
            "ChartHeight": { "$ref": "#/definitions/plotSize" },
            "Fonts": {
              "type": "object",
              "properties": {
                "AxisSize": { "$ref": "#/definitions/fontSize" },
                "LegendSize": { "$ref": "#/definitions/fontSize" },
                "OriginSize": { "$ref": "#/definitions/fontSize" },
                "WatermarkSize": { "$ref": "#/definitions/fontSize" },
                "FontFamilyName": {
                  "type": "string",
                  "enum": ["Arial", "Tahoma", "Times New Roman", "Microsoft Sans Serif"]
                }
              },
              "required": ["AxisSize", "LegendSize", "OriginSize", "FontFamilyName", "WatermarkSize"]
            }
          },
          "required": ["ChartWidth", "ChartHeight", "Fonts"]
        },

        "AllPlots": {
          "type": "array",
          "items": 
            {
              "type": "object",
              "properties": {
                "SectionId": {"type": "integer"},
                "Project": { "$ref": "#/definitions/nonEmptyString" },
                "Simulation": { "$ref": "#/definitions/nonEmptyString" }
              },
              "required": ["SectionId", "Project", "Simulation"]
            }
        },

        "GOFMergedPlots": {
          "type": "array",
          "items": 
            {
              "type": "object",
              "properties": {
                "SectionId": {"type": "integer"},
                "Caption": { "$ref": "#/definitions/nonEmptyString" },
                "PlotType": {
                  "type": "string",
                  "enum": ["predictedVsObserved", "residualsOverTime", "predictedVsObserved|residualsOverTime"]
                },
                "Groups": {
                  "type": "array",
                  "items": 
                    {
                      "type": "object",
                      "properties": {
                        "Caption": { "$ref": "#/definitions/nonEmptyString" },
                        "Symbol": { "$ref": "#/definitions/symbolType" },
                        "Simulations": {
                          "type": "array",
                          "items": 
                            {
                              "type": "object",
                              "properties": {
                                "Project": { "$ref": "#/definitions/nonEmptyString" },
                                "Simulation": { "$ref": "#/definitions/nonEmptyString" },
                                "Output": { "$ref": "#/definitions/nonEmptyString" },
                                "ObservedData": { "$ref": "#/definitions/nonEmptyString" },
                                "Color": { "$ref": "#/definitions/rgbColor" }
                              },
                              "required": ["Project", "Simulations", "Output", "ObservedData", "Color"]
                            }
                        }
                      },
                      "required": ["Caption", "Symbol", "Simulations"]
                    }
                }
              },
              "required": ["SectionId", "Caption", "PlotType", "Groups"]
            }
        },

        "ComparisonCTProfiles": {
          "type": "array",
          "items": 
            {
              "type": "object",
              "properties": {
                "SectionId": {"type": "integer"},
                "Caption": { "$ref": "#/definitions/nonEmptyString" },
                "SimulationDuration": { "$ref": "#/definitions/positiveNumber" },
                "TimeUnit": { "$ref": "#/definitions/timeUnit" },
                "Simulations": {
                  "type": "array",
                  "items": 
                    {
                      "type": "object",
                      "properties": {
                        "Project": { "$ref": "#/definitions/nonEmptyString" },
                        "Simulation": { "$ref": "#/definitions/nonEmptyString" },
                        "Output": { "$ref": "#/definitions/nonEmptyString" },
                        "ObservedData": { "$ref": "#/definitions/nonEmptyString" },
                        "Color": { "$ref": "#/definitions/rgbColor" },
                        "StartTime": {"type": "number"},
                        "TimeUnit": { "$ref": "#/definitions/timeUnit" }
                      },
                      "required": ["Project", "Simulation", "Output", "ObservedData", "Color", "StartTime", "TimeUnit"]
                    }
                }
              },
              "required": ["SectionId", "Caption", "SimulationDuration", "TimeUnit", "Simulations"]
            }
        },

        "DDIRatioPlots": {
          "type": "array",
          "items": 
            {
              "type": "object",
              "properties": {
                "SectionId": {"type": "integer"},
                "Caption": { "$ref": "#/definitions/nonEmptyString" },
                "PKParameter": {
                  "type": "string",
                  "enum": ["AUC", "CMAX", "AUC|CMAX"]
                },
                "PlotType": {
                  "type": "string",
                  "enum": ["predictedVsObserved", "residualsVsObserved", "predictedVsObserved|residualsVsObserved"]
                },
                "Groups": {
                  "type": "array",
                  "items": 
                    {
                      "type": "object",
                      "properties": {
                        "Caption": { "$ref": "#/definitions/nonEmptyString" },
                        "Color": { "$ref": "#/definitions/rgbColor" },
                        "Ratios": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": 
                            {
                              "Output": { "$ref": "#/definitions/nonEmptyString" },
                              "ObservedData": { "$ref": "#/definitions/nonEmptyString" },
                              "ObservedDataId": { "$ref": "#/definitions/nonEmptyString" },
                              "SimulationControl": {
                                "type": "object",
                                "properties": {
                                  "Project": { "$ref": "#/definitions/nonEmptyString" },
                                  "Simulation": { "$ref": "#/definitions/nonEmptyString" },
                                  "StartTime": {"type": "number"},
                                  "EndTime": {"type": "number"},
                                  "TimeUnit": { "$ref": "#/definitions/timeUnit" }
                                },
                              "required": ["Project", "Simulation", "StartTime", "EndTime", "TimeUnit"]
                              },
                              "SimulationDDI": {
                                "type": "object",
                                "properties": {
                                  "Project": { "$ref": "#/definitions/nonEmptyString" },
                                  "Simulation": { "$ref": "#/definitions/nonEmptyString" },
                                  "StartTime": {"type": "number"},
                                  "EndTime": {"type": "number"},
                                  "TimeUnit": { "$ref": "#/definitions/timeUnit" }
                                },
                              "required": ["Project", "Simulation", "StartTime", "EndTime", "TimeUnit"]
                              }
                            }
                          },
                          "required": ["Output", "ObservedData", "ObservedDataId", "SimulationControl", "SimulationDDI" ]
                        }
                      },
                      "required": ["Caption", "Color", "Ratios"]
                    }
                }
              },
              "required": ["SectionId", "Caption", "PKParameter", "PlotType", "Groups"]
            }
        }
      },
      "required": []
    },

    "Sections": { "$ref": "#/definitions/sections" },

    "Inputs":{
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Project": { "$ref": "#/definitions/nonEmptyString" },
          "Type": { "$ref": "#/definitions/buildingBlockOrSimulationType" },
          "Name": { "$ref": "#/definitions/nonEmptyString" },
          "SectionId": {"type": "integer"}
        }
      }
    }

  },
  "required": ["Projects", "ObservedDataSets", "Plots", "Sections", "Inputs"]
}

=== Open-Systems-Pharmacology/QualificationPlan/examples/PKRatio/input/PKRatio_quali_plan.json
{
  "$schema": "../../../schemas/OSP_Qualification_Plan_Schema.json",
  "Projects": [
    {
      "Id": "Amikacin",
      "Path": "Amikacin/Amikacin.json",
      "BuildingBlocks": []
    }
  ],
  "ObservedDataSets": [
    {
      "Id": "PK-Parameter",
      "Path": "Data/PK-Parameter.csv",
      "Type": "PKRatio"
    }
  ],
  "Plots": {
    "PlotSettings": {
      "ChartWidth": 500,
      "ChartHeight": 400,
      "Fonts": {
        "AxisSize": 11,
        "LegendSize": 9,
        "OriginSize": 9,
        "FontFamilyName": "Arial",
        "WatermarkSize": 40
      }
    },
    "AxesSettings": {
      "PKRatioPlots": [
        {
          "Type": "X",
          "Dimension": "Age",
          "Unit": "year(s)",
          "GridLines": false,
          "Scaling": "Linear"
        },
        {
          "Type": "Y",
          "Dimension": "Dimensionless",
          "Unit": "",
          "GridLines": false,
          "Scaling": "Log"
        }
      ]
    },
    "PKRatioPlots": [
      {
        "Title": "Observed versus Predicted Clearance Ratio",
        "PKParameters": ["CL"],
        "SectionId": 1,
        "Artifacts": [
          "Plot",
          "Table",
          "GMFE",
          "Measure"
        ],
        "Groups": [
          {
            "Caption": "Group caption #1",
            "Color": "#000000",
            "Symbol": "Circle",
            "PKRatios": [
              {
                "Project": "Amikacin",
                "Simulation": "Vogelstein#1",
                "Output": "Organism|PeripheralVenousBlood|Amikacin|Plasma (Peripheral Venous Blood)",
                "ObservedData": "PK-Parameter",
                "ObservedDataRecordId": 96
              },
              {
                "Project": "Amikacin",
                "Simulation": "Vogelstein#2",
                "Output": "Organism|PeripheralVenousBlood|Amikacin|Plasma (Peripheral Venous Blood)",
                "ObservedData": "PK-Parameter",
                "ObservedDataRecordId": 97
              }
            ]
          },
          {
            "Caption": "Group caption #2",
            "Color": "#FF0000",
            "Symbol": "Diamond",
            "PKRatios": [
              {
                "Project": "Amikacin",
                "Simulation": "Vogelstein#3",
                "Output": "Organism|PeripheralVenousBlood|Amikacin|Plasma (Peripheral Venous Blood)",
                "ObservedData": "PK-Parameter",
                "ObservedDataRecordId": 98
              }
            ]
          }
        ]
      },
      {
        "Title": "Observed versus Predicted Clearance Ratio",
        "PKParameters": ["CL"],
        "SectionId": 1,
        "Artifacts": [
          "Table",
          "Measure"
        ],
        "Groups": [
          {
            "Caption": "Group caption #2",
            "Color": "#FF0000",
            "Symbol": "Diamond",
            "PKRatios": [
              {
                "Project": "Amikacin",
                "Simulation": "Vogelstein#3",
                "Output": "Organism|PeripheralVenousBlood|Amikacin|Plasma (Peripheral Venous Blood)",
                "ObservedData": "PK-Parameter",
                "ObservedDataRecordId": 98
              }
            ]
          }
        ]
      }
    ]
  },
  "Inputs": [],
  "Sections": [
    {
      "Id": 1,
      "Title": "Qualification results",
      "Content": "Content/Results.md",
      "Sections": []
    }
  ]
}
